stok management table not filtering on combox and improving stock UI
openmrs/openmrs-esm-stock-management pull request #149
Opened 2024-06-21 14:08 UTC by samsonmwanzia

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2024-06-27 15:18 UTC, jabahum commented
@samsonmwanzia lets fix the build errors

2024-07-01 07:57 UTC, donaldkibet requested changes

2024-07-01 07:57 UTC, donaldkibet commented on src/core/components/card/metrics-card.scss
> +  background-color: #c2d4d4;
We should be using color tokens and spacing  from carbon
e.g 
```scss
margin-botton: layout.$spacing-05;
color: $color-gray-70;
```

the above are just example of how it should be done.

2024-07-02 11:52 UTC, makombe commented
Also, resolve the conflicts @samsonmwanzia

2024-08-21 06:49 UTC, hadijahkyampeire commented
@samsonmwanzia @donaldkibet @jabahum I am going to close this as well, I think it was fixed already.

2024-08-21 06:49 UTC, closed without merging