(Tests) 03-3758: stock operation tabs StockOperationSubmission test
openmrs/openmrs-esm-stock-management pull request #214
Opened 2024-09-23 05:30 UTC by lucyjemutai

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2024-09-26 06:13 UTC, lucyjemutai commented
@CynthiaKamau  @ODORA0

2024-09-30 08:55 UTC, ODORA0 requested changes

2024-09-30 08:55 UTC, ODORA0 commented on src/stock-operations/add-stock-operation/stock-operation-submission.test.tsx
> +    fireEvent.click(getByLabelText(/yes/i));
@lucyjemutai Just something small as I mentioned here

https://github.com/openmrs/openmrs-esm-stock-management/pull/225#issuecomment-2382439925

2024-10-01 06:05 UTC, ODORA0 approved these changes
LGTM

2024-10-01 06:05 UTC, merged