(Fix) FIxed the view all tabs on stock management dashboard , under inventory alerts, issuing and receiving
openmrs/openmrs-esm-stock-management pull request #248
Opened 2024-12-13 11:27 UTC by samsonmwanzia

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Fix the view all tabs on stock management dashboard under inventory alerts , issuing and receiving cards.

## Screenshots

## Related Issue

## Other

2024-12-16 17:24 UTC, jabahum requested changes

2024-12-16 17:24 UTC, jabahum commented on src/stock-home/stock-home-receiving-modal.component.tsx
> +    <Modal
lets use the stick to using the `openmrs/esm-framework` utilities for modal creation and management

2024-12-16 17:24 UTC, jabahum commented on src/stock-home/stock-home-issuing-modal.component.tsx
> +    <Modal
ditto

2024-12-16 17:24 UTC, jabahum commented on src/stock-home/stock-home-inventory-card.component.tsx
> +      {/* <Button
lets clean out on unused code if its nolonger necessary

2024-12-16 17:24 UTC, jabahum commented on src/stock-home/stock-home-issuing-card.component.tsx
> +      {/* <Button
remove unused code

2024-12-16 17:24 UTC, jabahum commented on src/stock-home/stock-home-issuing-card.component.tsx
> +      <IssuingStockModal open={isModalOpen} onClose={() => setModalOpen(false)} issuingStock={items} />
lets use `openmrs/esm-framework` modal utilities

2024-12-16 17:46 UTC, makombe commented
Thanks for the work @samsonmwanzia! Please create a ticket and also share some screenshots/video.

2024-12-16 17:49 UTC, samsonmwanzia commented
welcome i will send the video/screenshot tomorrow


On Mon, 16 Dec 2024 at 20:46, Makombe Kennedy ***@***.***>
wrote:

> Thanks for the work @samsonmwanzia <https://github.com/samsonmwanzia>!
> Please create a ticket and also share some screenshots/video.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openmrs/openmrs-esm-stock-management/pull/248#issuecomment-2546264324>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIUPZL7ZEH3BYPQLD7F5TT2F4GXVAVCNFSM6AAAAABTRZDE6OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBWGI3DIMZSGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-17 12:22 UTC, samsonmwanzia commented
https://github.com/user-attachments/assets/2bc99f49-2078-4c7e-8d49-bb7abec05c64

cleaned unused code too

2025-01-30 09:09 UTC, jabahum approved these changes

2025-01-30 09:09 UTC, merged